# Generated by Django 5.2.4 on 2025-07-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_question_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="character_class",
            field=models.CharField(
                choices=[("warrior", "Warrior"), ("mage", "Mage"), ("rogue", "Rogue")],
                default="warrior",
                max_length=20,
            ),
        ),
    ]
