# Generated by Django 5.2.4 on 2025-07-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_character_character_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="agility",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="character",
            name="intelligence",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="character",
            name="luck",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="character",
            name="strength",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="character",
            name="character_class",
            field=models.CharField(
                blank=True,
                choices=[("warrior", "Warrior"), ("mage", "Mage"), ("rogue", "Rogue")],
                max_length=20,
                null=True,
            ),
        ),
    ]
