# Generated by Django 5.2.4 on 2025-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_character_agility_character_intelligence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="stat_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="character",
            name="character_class",
            field=models.CharField(
                choices=[("warrior", "Warrior"), ("mage", "Mage"), ("rogue", "Rogue")],
                default="warrior",
                max_length=20,
            ),
        ),
    ]
