# Generated by Django 5.2.4 on 2025-07-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_character_stat_points_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("effect_strength", models.IntegerField(default=0)),
                ("effect_intelligence", models.IntegerField(default=0)),
                ("effect_agility", models.IntegerField(default=0)),
                ("effect_luck", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="characters", to="game.item"
            ),
        ),
    ]
