# Generated by Django 5.2.4 on 2025-07-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_item_character_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="equipped_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_on_body",
                to="game.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_feet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_on_feet",
                to="game.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_hand_left",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_on_hand_left",
                to="game.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_hand_right",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_on_hand_right",
                to="game.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_on_head",
                to="game.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_legs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_on_legs",
                to="game.item",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="slot",
            field=models.CharField(
                choices=[
                    ("head", "Head"),
                    ("body", "Body"),
                    ("legs", "Legs"),
                    ("feet", "Feet"),
                    ("hand_right", "Right Hand"),
                    ("hand_left", "Left Hand"),
                ],
                default="hand_right",
                max_length=20,
            ),
        ),
    ]
