# Generated by Django 5.2.4 on 2025-07-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_category_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="gold",
            field=models.IntegerField(default=0),
        ),
    ]
