# Generated by Django 5.2.4 on 2025-07-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_character_gold"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_available_in_shop",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
