# Generated by Django 5.2.4 on 2025-07-23 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_quest_questprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="questprogress",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questprogress",
            name="date_started",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questprogress",
            name="reward_claimed",
            field=models.BooleanField(default=False),
        ),
    ]
