# Generated by Django 5.2.4 on 2025-07-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_questprogress_date_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="armor",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="hp",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="character",
            name="hp_regeneration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="mana",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="character",
            name="mana_regeneration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="max_hp",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="character",
            name="max_mana",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="character",
            name="max_stamina",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="character",
            name="physical_max_damage",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="character",
            name="physical_min_damage",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_power",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="stamina",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="character",
            name="stamina_regeneration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
