# Generated by Django 5.2.4 on 2025-07-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_character_armor_character_hp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="armor",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="hp_bonus",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="mana_bonus",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="max_damage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="min_damage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="required_class",
            field=models.CharField(
                blank=True,
                choices=[("warrior", "Warrior"), ("mage", "Mage"), ("rogue", "Rogue")],
                help_text="If set, only characters of this class can equip the item.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="spell_power",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="stamina_bonus",
            field=models.IntegerField(default=0),
        ),
    ]
