# Generated by Django 5.2.4 on 2025-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_rename_agility_character_dexterity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="vitality",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="item",
            name="effect_vitality",
            field=models.IntegerField(default=0),
        ),
    ]
