# Generated by Django 5.2.4 on 2025-07-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0016_character_vitality_item_effect_vitality"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="damage_reduction",
            field=models.FloatField(default=0.0),
        ),
    ]
