# Generated by Django 5.2.4 on 2025-07-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_character_damage_reduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="hp_from_levels",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="mana_from_levels",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
