# Generated by Django 5.2.4 on 2025-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0018_character_hp_from_levels_character_mana_from_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="experience_to_next_level",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
