# Generated by Django 5.2.4 on 2025-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_character_experience_to_next_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enemy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("max_hp", models.PositiveIntegerField(default=100)),
                ("power", models.PositiveIntegerField(default=10)),
                ("armor", models.PositiveIntegerField(default=0)),
                ("gold_reward", models.PositiveIntegerField(default=0)),
                ("xp_reward", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
