# Generated by Django 5.2.4 on 2025-07-29 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0020_enemy"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="last_regen_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
