# Generated by Django 5.2.4 on 2025-07-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0021_character_last_regen_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="enemy",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("boss", "Boss"),
                ],
                default="easy",
                max_length=10,
            ),
        ),
    ]
